# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara'
require 'capybara-webkit'
require 'capybara/rails'
require 'capybara/cucumber'

Capybara.app_host = 'http://localhost:3000/'
Capybara.default_driver = :webkit
Capybara.default_max_wait_time = 10
Capybara.ignore_hidden_elements = true
Capybara.register_driver :webkit do |app| 
    Capybara::Webkit::Driver.new(app) 
end

ActionController::Base.allow_rescue = false



